title: DevExtreme Reactive Components
baseurl: "/devextreme-reactive"

markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-relative-links
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock

permalink: pretty

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
  - scope:
      path: react/grid/demos
      type: pages
    values:
      layout: demos
  - scope:
      path: react/grid/docs
      type: pages
    values:
      layout: docs
  - scope:
      path: react/core/docs
      type: pages
    values:
      layout: docs
