version: 2

jobs:
  Build Source:
    docker:
      - image: circleci/node:8
    working_directory: ~/circleci
    steps:
      - checkout
      - attach_workspace:
          at: ~/circleci

      - run: sudo npm i -g yarn
      - run: sudo chmod a+rwx /usr/local/bin/yarn

      - run: yarn --no-progress
      - run: yarn build

      - run: chmod -R 777 ~/circleci
      - persist_to_workspace:
          root: .
          paths: .

  Site:
    docker:
      - image: circleci/node:8
    working_directory: ~/circleci
    steps:
      - attach_workspace:
          at: ~/circleci
      - run: yarn build:site:docs

  Jest Tests & Linter:
    docker:
      - image: circleci/node:8
    working_directory: ~/circleci
    steps:
      - attach_workspace:
          at: ~/circleci
      - run: yarn lint
      - run: yarn test:ci

  TestCafe Tests:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/circleci
    steps:
      - checkout
      - attach_workspace:
          at: ~/circleci
      - run: yarn --no-progress
      - run: yarn testcafe:ci

      - store_test_results:
          path: /tmp/testcafe-test-results

workflows:
  version: 2
  tests:
    jobs:
      - Build Source
      - Jest Tests & Linter:
          requires:
            - Build Source
      - TestCafe Tests:
          requires:
            - Build Source
      - Site:
          requires:
            - Build Source
